#!/usr/bin/python
import os
import sys
import cgi
import time

sys.path.append('/home/tell/share/python')
from perlish import *

logdir="/home/envmonbox/log"
idlist="/home/envmonbox/clientid-list"

log_items = [
    "cpu_load",
    "cpu_temp",
    "room_temp",
    "room_humidity",
    "outdoor_temp",
]

log_dict = dict()
for item in log_items:
    log_dict[item] = None

form = cgi.FieldStorage();
clientid = form.getvalue('id')
remoteip = os.getenv('REMOTE_ADDR')

n_logitems = 0
for k in form.keys():
    val = form.getvalue(k)
    if(k in log_dict):
        log_dict[k] = val;
        n_logitems += 1

dbfp = open(logdir + "/mbdata-db", "a");
fprintf(dbfp, "--\nmbdata at %s\n", time.asctime())
fprintf(dbfp, "remote ip %s\n", remoteip)
fprintf(dbfp, "form=%s\n", str(form))
fprintf(dbfp, "%d logitems\n", n_logitems)
dbfp.flush()

def get_clientid_list(fn):
    iddict = dict()
    idfp = open(fn, "r");
    if(not idfp):
        fprintf(dbfp, "unable to open %s:\n", fn)
    for s in idfp:
        s = chomp(s) # todo remove all whitespace, not just last trailing
        if(int(s) > 0): # better valid checks
            iddict[s] = True
    idfp.close()
    return iddict

iddict = get_clientid_list(idlist) 
fprintf(dbfp, "get_clientid_list: %s\n", str(iddict))

if(not iddict.get(clientid, False)):
    fprintf(dbfp, "id %s not on the list\n", clientid)
    exit(0)

logfname = sprintf("%s/dlog.%s.0", logdir, clientid);
        
logfp = open(logfname, "a");
fprintf(logfp, "%s", time.strftime("%H:%M"))
for item in log_items:
    if(log_dict[item] is not None):
        fprintf(logfp, " %s", log_dict[item])
    else:
        fprintf(logfp, " -");
fprintf(logfp, "\n");
logfp.flush()

logfp.close()
    
#################

print("Content-type: text/html")
print()
print("""
<html>
<head><title>mybdata-test</title></head>
<body>
""")
print("<hr/>\n");
print("<b>all form values:</b><ul>\n");

for k in form.keys():
    printf("<li>%s=%s</li>\n", k, form.getvalue(k))
    
print("</ul>\n");
    
print("<hr/>\n");
printf("env: %s\n", str(os.environ))

print("""
</body>
</html>
""")

fprintf(dbfp, "done!\n");
dbfp.close()

