#!/usr/bin/python
import os
import sys
import cgi
import time
import math

logdir="/home/envmonbox/log"
idlist="/home/envmonbox/clientid-list"

sys.path.append("/home/envmonbox/lib/python");
from perlish import *
import mbconfig


global mbslist
mbslist = mbconfig.mbslist()
mbslist.init_static()
mbslist.setup_data()
    
form = cgi.FieldStorage();
clientid = form.getvalue('id')
remoteip = os.getenv('REMOTE_ADDR')

n_logitems = 0
for k in form.keys():
    val = form.getvalue(k)
    mbslist.set_value(k, val)
        
dbfp = open(logdir + "/mbdata-db", "a");
fprintf(dbfp, "--\nmbdata at %s\n", time.strftime("%c %z %Z"))
fprintf(dbfp, "remote ip %s\n", remoteip)
fprintf(dbfp, "form=%s\n", str(form))
fprintf(dbfp, "%d logitems\n", n_logitems)
fprintf(dbfp, "mbslist: %s\n", str(mbslist))
fprintf(dbfp, "\n");
dbfp.flush()

def numfield(s):
        if(s == '-' or s == '' or s == None or s == 'NaN' or s == 'nan' ):
                return math.nan
        else:
                return float(s)

def computed_fields_mbslist(mbslist):
    for s in mbslist.mblist:
        if(s.mbtype == 'mbgen'):
            if(s.gsource in mbslist.bytag):
                gsval = mbslist.bytag[ s.gsource ].last
                if(gsval is not None):
                    if(s.gfunc == "c_to_f"):
                        gval = float(gsval) * 1.8 + 32;
                        s.last = sprintf("%.1f", gval)
                
def get_clientid_list(fn):
    iddict = dict()
    idfp = open(fn, "r");
    if(not idfp):
        fprintf(dbfp, "unable to open %s:\n", fn)
    for s in idfp:
        s = chomp(s) # todo remove all whitespace, not just last trailing
        if(int(s) > 0): # better valid checks
            iddict[s] = True
    idfp.close()
    return iddict

def file_exists(f):
    try:
        st = os.stat(f)
        return True
    except FileNotFoundError:
        return False

iddict = get_clientid_list(idlist) 
#fprintf(dbfp, "get_clientid_list: %s\n", str(iddict))

if(not iddict.get(clientid, False)):
    fprintf(dbfp, "id %s not on the list\n", clientid)
    exit(0)

computed_fields_mbslist(mbslist)

timestr = time.strftime("%y%m%d")
logfname = sprintf("%s/dlog.%s.%s", logdir, clientid, timestr);

new_logfile = not(file_exists(logfname))
logfp = open(logfname, "a");

if(new_logfile):
    fprintf(logfp, "#Time");
    hdrs = mbslist.col_head_list()
    for h in hdrs:
        fprintf(logfp, " %s", h);
    fprintf(logfp, " floathour")
    fprintf(logfp, "\n")
        
tm = time.localtime()

fprintf(logfp, "%02d:%02d", tm.tm_hour, tm.tm_min)
for i in range(1, mbslist.maxcol+1):
    s = mbslist.bycolumn[i]
    if(s.last is not None):
        fprintf(logfp, " %s", s.last)
    else:
        fprintf(logfp, " NaN");
fprintf(logfp, " %6.3f", tm.tm_hour+tm.tm_min/60)
fprintf(logfp, "\n");
logfp.flush()

logfp.close()
    
#################

print("Content-type: text/html")
print()
print("""
<html>
<head><title>mybdata-test</title></head>
<body>
""")
print("<hr/>\n");
print("<b>all form values:</b><ul>\n");

for k in form.keys():
    printf("<li>%s=%s</li>\n", k, form.getvalue(k))
    
print("</ul>\n");
    
print("<hr/>\n");
printf("env: %s\n", str(os.environ))

print("""
</body>
</html>
""")

fprintf(dbfp, "done!\n");
dbfp.close()

