#!/usr/bin/python3
#!/home/tell/venv/bin/python3
# -*- coding: utf-8 -*-
#
# forward selected temperature readings from mqtt to guilfred
#
#

import time
import subprocess
import os
import sys
import re
import argparse
import json
import pprint
from os import *

sys.path.append('/home/envmonbox/lib/python');
from mbconfig import *
import mbutils
from perlish import *
import sgtmqtt

mymq = None
#minutes_per_update = 4
minutes_per_update = 1
seconds_per_update = 180
old_data_threshold = 900
messages_seen = 0
tmnow = time.localtime() 
last_send_minute = tmnow.tm_min
last_send_time = time.time()
fwid=1

parser =  argparse.ArgumentParser(description="gather environment monitoring data, from mqtt, and log to file");
parser.add_argument("--verbose", "-v", default=False, action='store_true');
parser.add_argument("--config", "-c", dest='configfile', default=None);
parser.add_argument("--norun", "-n", default=False, action='store_true');
parser.add_argument("--host", dest="mqhost", type=str, help="mqtt hostname", default="localhost");
args = parser.parse_args();
g_verbose = args.verbose

mqhost=args.mqhost
mymq = None
mylog = None

def guilfred_send_temp(tag, temp):
    cmd = sprintf("bin/gfexec '(nd-new-temp! %s %.1f)'", tag, temp );
    printf("send_guilfred: %s\n", cmd);
    if(not args.norun):
        system(cmd)

topics = [
    # mqtt topic 	            type        # forwarding/logging tag
    #[ "tele/tasmota_F99C40/SENSOR", '18b20_json' ,"indoor3_temp"],  # moved to bedroom
    [ "tele/tasmota_DACAF2/SENSOR", '18b20_json' ,"downstairs-temp"],  # sensor in living room
]

def init_topicinfo():
    global topicinfo
    global mbslist
    topicinfo = dict()
    for titem in list(topics):
        t = titem[0]
        ttype = titem[1]
        topicinfo[t] = dict()
        td = topicinfo[t] 
        td['last'] = None
        td['type'] = ttype
        td['lasttime'] = 0
        td['ftag'] = titem[2]
#    mbslist = mbconfig.mbslist()
#    mbslist.init_static()
#    mbslist.setup_data()
    printf("topicinfo=%s\n", str(topicinfo));

def on_connect(mq, userdata, flags, rc):
    print("Connected with result code "+str(rc))
    # Subscribing in on_connect() means that if we lose the connection and
    # reconnect then subscriptions will be renewed.
    if(mq):
        mq.subscribe("monbox/#")
        mq.subscribe("tele/#")

def on_message(msg):
    global topicinfo
    global messages_seen
    topic = str(msg.topic)

    # should use this path.  after mbslist rewrite to use sane yaml format.

    # maybe this ought to be an mbsensor or mbslist method?
    # if(topic in mbslist.bytopic):
    #     messages_seen += 1
    #     mbslist.bytopic[topic].lasttime = time.time()
    #     ttype = mbslist.bytopic[topic].mtype
    #     if(ttype == float):
    #         s = msg.payload.decode('ascii')
    #         mbslist.bytopic[topic].last = float(s)
    #     elif(ttype == str):
    #         mbslist.bytopic[topic].last = msg.payload.decode('ascii')
    #     elif(ttype == int):
    #         s = msg.payload.decode('ascii')
    #         mbslist.bytopic[topic].last = int(s, 0);
    #     elif(ttype == '18b20_json'):
    #         data = json.loads( msg.payload.decode('ascii') );
    #         tempstr = data['DS18B20']['Temperature'];
    #         mbslist.bytopic[topic].last = tempstr
    #     else:
    #         printf("unknown type %s for topic %s; treating as str\n", str(ttype), topic)
    #         mbslist.bytopic[topic].last = msg.payload.decode('ascii')

    if(topic in topicinfo):
        topicinfo[topic]['lasttime'] = time.time()
        ttype = topicinfo[topic]['type']
        if(ttype == float):
            s = msg.payload.decode('ascii')
            topicinfo[topic]['last'] = float(s)
        elif(ttype == str):
             topicinfo[topic]['last'] = msg.payload.decode('ascii')
        elif(ttype == int):
             s = msg.payload.decode('ascii')
             topicinfo[topic]['last'] = int(s, 0);
        elif(ttype == '18b20_json'):
            data = json.loads( msg.payload.decode('ascii') );
            tempstr = data['DS18B20']['Temperature'];
            topicinfo[topic]['last'] = tempstr
        else:
            printf("unknown type %s for topic %s; treating as str\n", str(ttype), topic)
            topicinfo[topic]['last'] = msg.payload.decode('ascii')
        if(g_verbose):             
            printf("msg %s topicinfo=%s\n", topic, topicinfo[topic])

        guilfred_send_temp( topicinfo[topic]['ftag'], topicinfo[topic]['last'])
            
    elif(g_verbose):
        printf("ignoring unknown topic %s\n", topic)

def periodic():
    global last_send_time
    global messages_seen
    now = time.time()
    pass

def print_current():
    "print current info on all known topics"
    global topicinfo
    for t, td in topicinfo.items():
        printf(" %30s %12d %10s\n", t, td['lasttime'], str(td['last']))
#    for mbs in mbslist.mblist:
#        printf(" %30s %12d %10s\n", mbs.ftag, mbs.lasttime, str(mbs.last))
    printf("\n");


def main():
    global mymq
    global fwid
    chdir("/home/ha")
    init_topicinfo()
    mymq = sgtmqtt.sgtmqtt(mqhost=mqhost)
    mymq.on_message = on_message
    mymq.mq.on_connect = on_connect
    mymq.periodic_callback = periodic
#    mymq.nomqtt_callback = nomq_callback
    mymq.select_loop(5)	

main()
